language: python
matrix:
  fast_finish: true
  include:
    - python: "2.7"
    - python: "3.7"
      dist: xenial
install:
  - pip install nose
  - pip install coveralls
script: nosetests --with-coverage --cover-package=batlog2csv
after_success:
  coveralls
